name: Deploy Gatsby repo to Bunny.net

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Upload all files to Bunny Storage
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: sg.storage.bunnycdn.com
          username: bl1d
          password: ${{ secrets.BUNNY_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /bl1d/
          log-level: minimal
          state-name: .ftp-deploy-sync-state.json
